22-authentication-authorization/config/routes.rb
Rails.application.routes.draw do
  resources :teachers
  resources :students, only: [:show, :new, :index, :create]
  get '/login', to: "auth#login", as: "login"
  post '/login', to: "auth#verify"
  get '/logout', to: "auth#logout", as: "logout"
  root 'students#index'
end

22-authentication-authorization/app/models/cohort.rb
class Cohort < ApplicationRecord
  has_many :students
end

22-authentication-authorization/app/models/student.rb
class Student < ApplicationRecord
  belongs_to :cohort, optional: true

  validates :name, :email, presence: true
  validates :email, uniqueness: true
end

22-authentication-authorization/app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :cohorts
  validates :email, uniqueness: true
  validates :username, presence: true
  # has_many :students, through: :cohorts
end

22-authentication-authorization/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :logged_in?, :security
  #redirect the user to the login page
  def security
    if !logged_in?
      flash[:login_please] = "Please Exist"
      redirect_to login_path
    end
  end

  def logged_in?
    session[:teacher_id]
  end

  def current_user
    if logged_in?
      User.find(session[:teacher_id])
    end
  end
end

22-authentication-authorization/app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def login
  end

  def verify
    # byebug
    @teacher = Teacher.find_by(username: params[:username])
    #Initialize an auth_token
    session[:teacher_id] = @teacher.id
    if @teacher && @teacher.email == params[:email]
        redirect_to students_path
    else
      flash[:message] = "Yo, You don't exist"
      render :login
    end
  end

  def logout
    session.clear
    redirect_to login_path
  end
end

22-authentication-authorization/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :security

  def index
      @students = Student.all
  end

  def show
      @student = Student.find_by(id: params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to @student
    else
      render :new
    end

  end

  private
  def student_params
    params.require(:student).permit(:name, :email, :cohort_id)
  end
end

22-authentication-authorization/app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def new
    @teacher = Teacher.new
  end

  def create
    # byebug
    @teacher = Teacher.new(set_params)
    if @teacher.save
      redirect_to students_path
    else
      flash[:message] = "Some details are wrong. Fix It"
      render :new
    end
  end

  private
  def set_params
    params.require(:teacher).permit(:username,:email)
  end
end

22-authentication-authorization/app/helpers/application_helper.rb
module ApplicationHelper
end

22-authentication-authorization/app/helpers/students_helper.rb
module StudentsHelper
end

22-authentication-authorization/app/helpers/teachers_helper.rb
module TeachersHelper
end

22-authentication-authorization/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentLister</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
  </head>
  <div class="ui teal inverted menu">
    <a href="/" class="item">
      <h1>Student Lister</h1>
    </a>
      <div class="right menu">
        <% if logged_in? %>
          <%= link_to 'Create a New Student', new_student_path, {class: 'item'} %>
          <%= link_to 'Logout', logout_path, {class: 'item'} %>
        <% end %>

      </div>
  </div>
  <body>
    <div class="ui centered grid ">
      <div class="eight wide column">

        <%= yield %>

      </div>
    </div>
  </body>
</html>

22-authentication-authorization/app/views/teachers/new.erb
<%= flash[:message] %>

<%= form_with url: login_path do |form| %>
  <%= form.text_field :username %>
  <%= form.text_field :email %>
  <%= form.submit %>
<% end %>